# Generated by Django 3.1.2 on 2020-12-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('year', models.DateTimeField(null=True)),
                ('land', models.CharField(max_length=30)),
                ('type_of_stock', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='tillage',
            old_name='organic_phospheros_applied',
            new_name='organic_phospherus_applied',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='land',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='location',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='name',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='type_of_stock',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='year',
        ),
    ]
