# Generated by Django 3.1.2 on 2021-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='land',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='grassland',
            name='type_of_stock',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
