# Generated by Django 3.1.2 on 2021-04-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slurry_Storage',
        ),
    ]
