# Generated by Django 3.1.2 on 2021-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
