# Generated by Django 3.1.2 on 2020-12-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0002_auto_20201217_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='herd_no',
            field=models.IntegerField(null=True),
        ),
    ]
