# Generated by Django 3.1.2 on 2021-01-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0002_auto_20210112_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='land',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='type_of_stock',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
