# Generated by Django 3.1.2 on 2021-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0003_auto_20210127_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
