# Generated by Django 3.1.2 on 2021-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0003_slurry_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurry_storage',
            name='num_containers',
            field=models.IntegerField(null=True),
        ),
    ]
