# Generated by Django 3.1.2 on 2021-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0003_auto_20210112_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='county',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
