# Generated by Django 3.1.2 on 2021-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0004_slurry_storage_num_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurry_storage',
            name='manure_m3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='slurry_storage',
            name='slurry_m3',
            field=models.FloatField(null=True),
        ),
    ]
