# Generated by Django 3.1.2 on 2021-01-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0004_auto_20210127_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassland',
            name='date_taken',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='grassland',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
