# Generated by Django 3.1.2 on 2021-01-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0004_farmer_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassland',
            name='land',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='county',
            field=models.CharField(choices=[('1', 'Carlow'), ('2', 'Cavan'), ('3', 'Clare'), ('4', 'Cork'), ('5', 'Donegal'), ('6', 'Dublin'), ('7', 'Galway'), ('8', 'Kerry'), ('9', 'Kildare'), ('10', 'Kilkenny'), ('11', 'Laois'), ('12', 'Leitrim'), ('13', 'Limerick'), ('14', 'Longford'), ('15', 'Louth'), ('16', 'Mayo'), ('17', 'Meath'), ('18', 'Monaghan'), ('19', 'Offaly'), ('20', 'Roscommon'), ('21', 'Sligo'), ('22', 'Tipperary'), ('23', 'Waterford'), ('24', 'Westmeath'), ('25', 'Wexford'), ('26', 'Wicklow')], max_length=30, null=True),
        ),
    ]
