# Generated by Django 3.1.2 on 2021-04-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0005_auto_20210408_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurry_storage',
            name='manure_m3',
        ),
        migrations.RemoveField(
            model_name='slurry_storage',
            name='slurry_m3',
        ),
        migrations.AddField(
            model_name='monthly_livestock_numbers',
            name='manure_m3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='monthly_livestock_numbers',
            name='slurry_m3',
            field=models.FloatField(null=True),
        ),
    ]
