# Generated by Django 3.1.2 on 2021-01-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0005_auto_20210114_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='area_reseeded',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='owned_land',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='rented_land',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='total_grass_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='total_tillage_area',
            field=models.IntegerField(null=True),
        ),
    ]
