# Generated by Django 3.1.2 on 2021-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0006_auto_20210408_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='zone',
            field=models.CharField(default='a', max_length=30),
        ),
    ]
