# Generated by Django 3.1.2 on 2021-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0006_auto_20210114_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='date_taken',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='k_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='k_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='p_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='p_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='ph',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='sample_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grassland',
            name='sample_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
