# Generated by Django 3.1.2 on 2021-02-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0006_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_livestock_numbers',
            name='monthly_livestock_numbers',
            field=models.TextField(max_length=65535),
        ),
    ]
