# Generated by Django 3.1.2 on 2021-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0007_auto_20210121_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='type_of_feed',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
