# Generated by Django 3.1.2 on 2021-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0007_farmer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='zone',
            field=models.CharField(max_length=30),
        ),
    ]
