# Generated by Django 3.1.2 on 2021-04-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0008_auto_20210409_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurry_storage',
            name='zone',
        ),
    ]
