# Generated by Django 3.1.2 on 2021-02-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0008_auto_20210131_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly_livestock_numbers',
            name='monthly_livestock_numbers',
            field=models.TextField(null=True),
        ),
    ]
