# Generated by Django 3.1.2 on 2021-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0008_grassland_type_of_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='feed_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
