# Generated by Django 3.1.2 on 2021-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0009_grassland_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='number_of_animals',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
