# Generated by Django 3.1.2 on 2021-02-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0009_auto_20210131_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_dairy_cows', models.IntegerField(null=True)),
                ('number_suckler_cows', models.IntegerField(null=True)),
                ('number_cattle1', models.IntegerField(null=True)),
                ('number_cattle2', models.IntegerField(null=True)),
                ('number_cattle3', models.IntegerField(null=True)),
                ('number_mountain_ewe', models.IntegerField(null=True)),
                ('number_lowland_ewe', models.IntegerField(null=True)),
                ('number_mountain_hogget', models.IntegerField(null=True)),
                ('number_lowland_hogget', models.IntegerField(null=True)),
                ('number_goats', models.IntegerField(null=True)),
                ('number_horse1', models.IntegerField(null=True)),
                ('number_horse2', models.IntegerField(null=True)),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer')),
            ],
        ),
    ]
