# Generated by Django 3.1.2 on 2021-04-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0010_auto_20210413_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurry_storage',
            name='num_containers',
        ),
    ]
