# Generated by Django 3.1.2 on 2021-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0010_grassland_number_of_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='feed_tonnage',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
