# Generated by Django 3.1.2 on 2021-02-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0010_farmer_livestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=30)),
                ('kg_per_tonne_fed', models.IntegerField(null=True)),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer')),
            ],
        ),
    ]
