# Generated by Django 3.1.2 on 2021-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0011_remove_slurry_storage_num_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurry_storage',
            name='manure_produced',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='slurry_storage',
            name='max_storage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='slurry_storage',
            name='space_available',
            field=models.FloatField(null=True),
        ),
    ]
