# Generated by Django 3.1.2 on 2021-02-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0011_farmer_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_feed',
            name='feed_name',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
