# Generated by Django 3.1.2 on 2021-01-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0011_grassland_feed_tonnage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='herd_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
