# Generated by Django 3.1.2 on 2021-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0012_auto_20210126_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='total_land_area',
            field=models.IntegerField(null=True),
        ),
    ]
