# Generated by Django 3.1.2 on 2021-04-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0012_auto_20210415_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurry_storage',
            name='manure_produced',
        ),
    ]
