# Generated by Django 3.1.2 on 2021-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0013_auto_20210204_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_cattle1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_cattle2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_cattle3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_dairy_cows',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_goats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_horse1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_horse2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_lowland_ewe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_lowland_hogget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_mountain_ewe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_mountain_hogget',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer_livestock',
            name='number_suckler_cows',
            field=models.IntegerField(null=True),
        ),
    ]
