# Generated by Django 3.1.2 on 2021-01-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0013_grassland_total_land_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='herd_no',
        ),
        migrations.AddField(
            model_name='grassland',
            name='herd_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer'),
        ),
    ]
