# Generated by Django 3.1.2 on 2021-04-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0013_remove_slurry_storage_manure_produced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tillage',
        ),
    ]
