# Generated by Django 3.1.2 on 2021-01-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0014_auto_20210126_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grassland',
            old_name='herd_no',
            new_name='farmer_id',
        ),
        migrations.AddField(
            model_name='farmer',
            name='herd_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
