# Generated by Django 3.1.2 on 2021-02-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0014_auto_20210204_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farmer_Feed',
            new_name='Feed_Types',
        ),
    ]
