# Generated by Django 3.1.2 on 2021-02-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0015_auto_20210210_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer')),
            ],
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
    ]
