# Generated by Django 3.1.2 on 2021-04-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0015_delete_fertilzer_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grassland',
            name='concentrateFed',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='k_index',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='k_value',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='lime_required',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='p_index',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='p_value',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='reseeding',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='sample_area',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='sample_code',
        ),
        migrations.RemoveField(
            model_name='grassland',
            name='soil_samples',
        ),
    ]
