# Generated by Django 3.1.2 on 2021-02-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0016_auto_20210210_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straight', models.CharField(max_length=30)),
                ('compound', models.CharField(max_length=30)),
            ],
        ),
    ]
