# Generated by Django 3.1.2 on 2021-02-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0017_feeds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeds',
        ),
    ]
