# Generated by Django 3.1.2 on 2021-02-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0018_delete_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_feed',
            name='number_beans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_beat_pulp_unmolassed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_beat_pulps_molassed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_citrus_pulp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_compound',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_copra',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_cotton_seed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_distillers_grain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_lucerne',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_maize',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_maize_distiller',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_maize_germ',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_maize_gluten',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_oats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_palm_kernel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_peas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_rapeseed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_soya_bean',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_soya_hulls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_sunflower',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer_feed',
            name='number_wheat',
            field=models.IntegerField(null=True),
        ),
    ]
