# Generated by Django 3.1.2 on 2021-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0019_auto_20210210_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='time_rented',
            field=models.IntegerField(null=True),
        ),
    ]
