# Generated by Django 3.1.2 on 2021-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0020_grassland_time_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportation',
            name='export',
        ),
        migrations.RemoveField(
            model_name='exportation',
            name='exportation_original_stocking_rate',
        ),
        migrations.RemoveField(
            model_name='exportation',
            name='new_stocking_rate',
        ),
        migrations.RemoveField(
            model_name='exportation',
            name='person_accepting_import',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='exportation_details',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='importation_original_stocking_rate',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='nitrates_and_potassium_figures',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='organic_manure_breakdown',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='stocking_rate_including_import',
        ),
        migrations.AddField(
            model_name='exportation',
            name='farmyard_manure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exportation',
            name='slurry',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importation',
            name='farmyard_manure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importation',
            name='slurry',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='county',
            field=models.CharField(choices=[('24', 'Carlow'), ('27', 'Cavan'), ('32', 'Clare'), ('37', 'Cork'), ('38', 'Donegal'), ('17', 'Dublin'), ('34', 'Galway'), ('45', 'Kerry'), ('18', 'Kildare'), ('23', 'Kilkenny'), ('22', 'Laois'), ('33', 'Leitrim'), ('26', 'Limerick'), ('23', 'Longford'), ('20', 'Louth'), ('40', 'Mayo'), ('19', 'Meath'), ('23', 'Monaghan'), ('20', 'Offaly'), ('26', 'Roscommon'), ('32', 'Sligo'), ('27', 'Tipperary'), ('31', 'Waterford'), ('21', 'Westmeath'), ('25', 'Wexford'), ('33', 'Wicklow')], max_length=30, null=True),
        ),
    ]
