# Generated by Django 3.1.2 on 2021-04-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0021_auto_20210331_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportation',
            name='farmer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer'),
        ),
        migrations.AddField(
            model_name='importation',
            name='farmer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teagasc.farmer'),
        ),
    ]
