# Generated by Django 3.1.2 on 2021-04-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0022_auto_20210401_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportation',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='importation',
            name='farmer_id',
        ),
    ]
