# Generated by Django 3.1.2 on 2021-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0023_auto_20210401_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='wholefarm_stocking_rate',
            field=models.FloatField(null=True),
        ),
    ]
