# Generated by Django 3.1.2 on 2021-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0024_grassland_wholefarm_stocking_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_assessed',
            field=models.IntegerField(default=0, max_length=1, null=True),
        ),
    ]
