# Generated by Django 3.1.2 on 2021-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0025_farmer_is_assessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='is_assessed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
