# Generated by Django 3.1.2 on 2021-04-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0026_auto_20210405_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='herd_no',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
