# Generated by Django 3.1.2 on 2021-04-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0028_auto_20210405_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportation',
            name='farmer_id',
        ),
    ]
