# Generated by Django 3.1.2 on 2021-04-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0031_auto_20210405_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportation',
            old_name='farmer',
            new_name='farmer_id',
        ),
    ]
