# Generated by Django 3.1.2 on 2021-04-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0032_auto_20210405_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportation',
            name='nitrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exportation',
            name='phosphate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importation',
            name='nitrates',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='importation',
            name='phosphate',
            field=models.IntegerField(null=True),
        ),
    ]
