# Generated by Django 3.1.2 on 2021-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0033_auto_20210407_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassland',
            name='lsu',
            field=models.FloatField(null=True),
        ),
    ]
