# Generated by Django 3.1.2 on 2021-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0034_grassland_lsu'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_livestock_numbers',
            name='lsu',
            field=models.FloatField(null=True),
        ),
    ]
