# Generated by Django 3.1.2 on 2020-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teagasc', '0003_farmer_herd_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
